version: '3'
services:
  # app:
  #   build: .
  #   container_name: ${APP_NAME}
  #   environment:
  #     - POSTGRES_HOST=${APP_NAME}-db
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  db:
    image: postgres:15.4-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - devplus-pg:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  devplus-pg:
