version: '3'
services:
  db:
    image: postgres:15.4-alpine
    container_name: ${APP_NAME}-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - dev-final:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  dev-final:
